checksumBehavior: update

enableTelemetry: false

compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard

nodeLinker: pnp

pnpEnableEsmLoader: true

pnpMode: loose
